//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proekt4
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Номенклатура.
    /// </summary>
    // *** Start programmer edit section *** (Номенклатура CustomAttributes)

    // *** End programmer edit section *** (Номенклатура CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("НоменклатураE", new string[] {
            "Наименование as \'Наименование\'"})]
    [View("НоменклатураL", new string[] {
            "Наименование as \'Наименование\'"})]
    public class Номенклатура : ICSSoft.STORMNET.DataObject
    {
        
        private int fКод;
        
        private string fНаименование;
        
        private IIS.Proekt4.ЭкоКласс fЭкоКласс;
        
        private IIS.Proekt4.ЗащСвойства fЗащСвойства;
        
        // *** Start programmer edit section *** (Номенклатура CustomMembers)

        // *** End programmer edit section *** (Номенклатура CustomMembers)

        
        /// <summary>
        /// Код.
        /// </summary>
        // *** Start programmer edit section *** (Номенклатура.Код CustomAttributes)

        // *** End programmer edit section *** (Номенклатура.Код CustomAttributes)
        public virtual int Код
        {
            get
            {
                // *** Start programmer edit section *** (Номенклатура.Код Get start)

                // *** End programmer edit section *** (Номенклатура.Код Get start)
                int result = this.fКод;
                // *** Start programmer edit section *** (Номенклатура.Код Get end)

                // *** End programmer edit section *** (Номенклатура.Код Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Номенклатура.Код Set start)

                // *** End programmer edit section *** (Номенклатура.Код Set start)
                this.fКод = value;
                // *** Start programmer edit section *** (Номенклатура.Код Set end)

                // *** End programmer edit section *** (Номенклатура.Код Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Номенклатура.Наименование CustomAttributes)

        // *** End programmer edit section *** (Номенклатура.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Номенклатура.Наименование Get start)

                // *** End programmer edit section *** (Номенклатура.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (Номенклатура.Наименование Get end)

                // *** End programmer edit section *** (Номенклатура.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Номенклатура.Наименование Set start)

                // *** End programmer edit section *** (Номенклатура.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Номенклатура.Наименование Set end)

                // *** End programmer edit section *** (Номенклатура.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Номенклатура.
        /// </summary>
        // *** Start programmer edit section *** (Номенклатура.ЗащСвойства CustomAttributes)

        // *** End programmer edit section *** (Номенклатура.ЗащСвойства CustomAttributes)
        [PropertyStorage(new string[] {
                "ЗащСвойства"})]
        [NotNull()]
        public virtual IIS.Proekt4.ЗащСвойства ЗащСвойства
        {
            get
            {
                // *** Start programmer edit section *** (Номенклатура.ЗащСвойства Get start)

                // *** End programmer edit section *** (Номенклатура.ЗащСвойства Get start)
                IIS.Proekt4.ЗащСвойства result = this.fЗащСвойства;
                // *** Start programmer edit section *** (Номенклатура.ЗащСвойства Get end)

                // *** End programmer edit section *** (Номенклатура.ЗащСвойства Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Номенклатура.ЗащСвойства Set start)

                // *** End programmer edit section *** (Номенклатура.ЗащСвойства Set start)
                this.fЗащСвойства = value;
                // *** Start programmer edit section *** (Номенклатура.ЗащСвойства Set end)

                // *** End programmer edit section *** (Номенклатура.ЗащСвойства Set end)
            }
        }
        
        /// <summary>
        /// Номенклатура.
        /// </summary>
        // *** Start programmer edit section *** (Номенклатура.ЭкоКласс CustomAttributes)

        // *** End programmer edit section *** (Номенклатура.ЭкоКласс CustomAttributes)
        [PropertyStorage(new string[] {
                "ЭкоКласс"})]
        [NotNull()]
        public virtual IIS.Proekt4.ЭкоКласс ЭкоКласс
        {
            get
            {
                // *** Start programmer edit section *** (Номенклатура.ЭкоКласс Get start)

                // *** End programmer edit section *** (Номенклатура.ЭкоКласс Get start)
                IIS.Proekt4.ЭкоКласс result = this.fЭкоКласс;
                // *** Start programmer edit section *** (Номенклатура.ЭкоКласс Get end)

                // *** End programmer edit section *** (Номенклатура.ЭкоКласс Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Номенклатура.ЭкоКласс Set start)

                // *** End programmer edit section *** (Номенклатура.ЭкоКласс Set start)
                this.fЭкоКласс = value;
                // *** Start programmer edit section *** (Номенклатура.ЭкоКласс Set end)

                // *** End programmer edit section *** (Номенклатура.ЭкоКласс Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "НоменклатураE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View НоменклатураE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("НоменклатураE", typeof(IIS.Proekt4.Номенклатура));
                }
            }
            
            /// <summary>
            /// "НоменклатураL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View НоменклатураL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("НоменклатураL", typeof(IIS.Proekt4.Номенклатура));
                }
            }
        }
    }
}
