//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proekt4
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Подразделение.
    /// </summary>
    // *** Start programmer edit section *** (Подразделение CustomAttributes)

    // *** End programmer edit section *** (Подразделение CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПодразделениеE", new string[] {
            "Код as \'Код\'",
            "Название as \'Название\'"})]
    [View("ПодразделениеL", new string[] {
            "Код as \'Код\'",
            "Название as \'Название\'"})]
    public class Подразделение : ICSSoft.STORMNET.DataObject
    {
        
        private int fКод;
        
        private string fНазвание;
        
        // *** Start programmer edit section *** (Подразделение CustomMembers)

        // *** End programmer edit section *** (Подразделение CustomMembers)

        
        /// <summary>
        /// Код.
        /// </summary>
        // *** Start programmer edit section *** (Подразделение.Код CustomAttributes)

        // *** End programmer edit section *** (Подразделение.Код CustomAttributes)
        public virtual int Код
        {
            get
            {
                // *** Start programmer edit section *** (Подразделение.Код Get start)

                // *** End programmer edit section *** (Подразделение.Код Get start)
                int result = this.fКод;
                // *** Start programmer edit section *** (Подразделение.Код Get end)

                // *** End programmer edit section *** (Подразделение.Код Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Подразделение.Код Set start)

                // *** End programmer edit section *** (Подразделение.Код Set start)
                this.fКод = value;
                // *** Start programmer edit section *** (Подразделение.Код Set end)

                // *** End programmer edit section *** (Подразделение.Код Set end)
            }
        }
        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (Подразделение.Название CustomAttributes)

        // *** End programmer edit section *** (Подразделение.Название CustomAttributes)
        [StrLen(255)]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (Подразделение.Название Get start)

                // *** End programmer edit section *** (Подразделение.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (Подразделение.Название Get end)

                // *** End programmer edit section *** (Подразделение.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Подразделение.Название Set start)

                // *** End programmer edit section *** (Подразделение.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (Подразделение.Название Set end)

                // *** End programmer edit section *** (Подразделение.Название Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПодразделениеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПодразделениеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПодразделениеE", typeof(IIS.Proekt4.Подразделение));
                }
            }
            
            /// <summary>
            /// "ПодразделениеL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПодразделениеL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПодразделениеL", typeof(IIS.Proekt4.Подразделение));
                }
            }
        }
    }
}
