//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proekt4
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Эко класс.
    /// </summary>
    // *** Start programmer edit section *** (ЭкоКласс CustomAttributes)

    // *** End programmer edit section *** (ЭкоКласс CustomAttributes)
    [AutoAltered()]
    [Caption("Эко класс")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЭкоКлассE", new string[] {
            "Код as \'Код\'",
            "Наименование as \'Наименование\'"})]
    [View("ЭкоКлассL", new string[] {
            "Код as \'Код\'",
            "Наименование as \'Наименование\'"})]
    public class ЭкоКласс : ICSSoft.STORMNET.DataObject
    {
        
        private int fКод;
        
        private string fНаименование;
        
        // *** Start programmer edit section *** (ЭкоКласс CustomMembers)

        // *** End programmer edit section *** (ЭкоКласс CustomMembers)

        
        /// <summary>
        /// Код.
        /// </summary>
        // *** Start programmer edit section *** (ЭкоКласс.Код CustomAttributes)

        // *** End programmer edit section *** (ЭкоКласс.Код CustomAttributes)
        public virtual int Код
        {
            get
            {
                // *** Start programmer edit section *** (ЭкоКласс.Код Get start)

                // *** End programmer edit section *** (ЭкоКласс.Код Get start)
                int result = this.fКод;
                // *** Start programmer edit section *** (ЭкоКласс.Код Get end)

                // *** End programmer edit section *** (ЭкоКласс.Код Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЭкоКласс.Код Set start)

                // *** End programmer edit section *** (ЭкоКласс.Код Set start)
                this.fКод = value;
                // *** Start programmer edit section *** (ЭкоКласс.Код Set end)

                // *** End programmer edit section *** (ЭкоКласс.Код Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (ЭкоКласс.Наименование CustomAttributes)

        // *** End programmer edit section *** (ЭкоКласс.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (ЭкоКласс.Наименование Get start)

                // *** End programmer edit section *** (ЭкоКласс.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (ЭкоКласс.Наименование Get end)

                // *** End programmer edit section *** (ЭкоКласс.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЭкоКласс.Наименование Set start)

                // *** End programmer edit section *** (ЭкоКласс.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (ЭкоКласс.Наименование Set end)

                // *** End programmer edit section *** (ЭкоКласс.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЭкоКлассE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЭкоКлассE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЭкоКлассE", typeof(IIS.Proekt4.ЭкоКласс));
                }
            }
            
            /// <summary>
            /// "ЭкоКлассL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЭкоКлассL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЭкоКлассL", typeof(IIS.Proekt4.ЭкоКласс));
                }
            }
        }
    }
}
